use flagsdb;

db.flags.remove({});

db.flags.insert([

{
  "id": 1,
  "name": "Scotland",
  "flagLEDs":[
    // hardcode of the scotland flag.
    // row 1
    {"position": [0, 0], "colour": "white", "status": "off"},
    {"position": [0, 1], "colour": "white", "status": "off"},
    {"position": [0, 2], "colour": "blue", "status": "off"},
    {"position": [0, 3], "colour": "blue", "status": "off"},
    {"position": [0, 4], "colour": "blue", "status": "off"},
    {"position": [0, 5], "colour": "blue", "status": "off"},
    {"position": [0, 6], "colour": "blue", "status": "off"},
    {"position": [0, 7], "colour": "blue", "status": "off"},
    {"position": [0, 8], "colour": "blue", "status": "off"},
    {"position": [0, 9], "colour": "blue", "status": "off"},
    {"position": [0, 10], "colour": "white", "status": "off"},
    {"position": [0, 11], "colour": "white", "status": "off"},
    // row 2
    {"position": [1, 0], "colour": "blue", "status": "off"},
    {"position": [1, 1], "colour": "white", "status": "off"},
    {"position": [1, 2], "colour": "white", "status": "off"},
    {"position": [1, 3], "colour": "blue", "status": "off"},
    {"position": [1, 4], "colour": "blue", "status": "off"},
    {"position": [1, 5], "colour": "blue", "status": "off"},
    {"position": [1, 6], "colour": "blue", "status": "off"},
    {"position": [1, 7], "colour": "blue", "status": "off"},
    {"position": [1, 8], "colour": "blue", "status": "off"},
    {"position": [1, 9], "colour": "white", "status": "off"},
    {"position": [1, 10], "colour": "white", "status": "off"},
    {"position": [1, 11], "colour": "blue", "status": "off"},
    // row 3
    {"position": [2, 0], "colour": "blue", "status": "off"},
    {"position": [2, 1], "colour": "blue", "status": "off"},
    {"position": [2, 2], "colour": "white", "status": "off"},
    {"position": [2, 3], "colour": "white", "status": "off"},
    {"position": [2, 4], "colour": "blue", "status": "off"},
    {"position": [2, 5], "colour": "blue", "status": "off"},
    {"position": [2, 6], "colour": "blue", "status": "off"},
    {"position": [2, 7], "colour": "blue", "status": "off"},
    {"position": [2, 8], "colour": "white", "status": "off"},
    {"position": [2, 9], "colour": "white", "status": "off"},
    {"position": [2, 10], "colour": "blue", "status": "off"},
    {"position": [2, 11], "colour": "blue", "status": "off"},
    // row 4
    {"position": [3, 0], "colour": "blue", "status": "off"},
    {"position": [3, 1], "colour": "blue", "status": "off"},
    {"position": [3, 2], "colour": "blue", "status": "off"},
    {"position": [3, 3], "colour": "white", "status": "off"},
    {"position": [3, 4], "colour": "white", "status": "off"},
    {"position": [3, 5], "colour": "blue", "status": "off"},
    {"position": [3, 6], "colour": "blue", "status": "off"},
    {"position": [3, 7], "colour": "white", "status": "off"},
    {"position": [3, 8], "colour": "white", "status": "off"},
    {"position": [3, 9], "colour": "blue", "status": "off"},
    {"position": [3, 10], "colour": "blue", "status": "off"},
    {"position": [3, 11], "colour": "blue", "status": "off"},
    // row 5
    {"position": [4, 0], "colour": "blue", "status": "off"},
    {"position": [4, 1], "colour": "blue", "status": "off"},
    {"position": [4, 2], "colour": "blue", "status": "off"},
    {"position": [4, 3], "colour": "blue", "status": "off"},
    {"position": [4, 4], "colour": "white", "status": "off"},
    {"position": [4, 5], "colour": "white", "status": "off"},
    {"position": [4, 6], "colour": "white", "status": "off"},
    {"position": [4, 7], "colour": "white", "status": "off"},
    {"position": [4, 8], "colour": "blue", "status": "off"},
    {"position": [4, 9], "colour": "blue", "status": "off"},
    {"position": [4, 10], "colour": "blue", "status": "off"},
    {"position": [4, 11], "colour": "blue", "status": "off"},
    // row 6
    {"position": [5, 0], "colour": "blue", "status": "off"},
    {"position": [5, 1], "colour": "blue", "status": "off"},
    {"position": [5, 2], "colour": "blue", "status": "off"},
    {"position": [5, 3], "colour": "blue", "status": "off"},
    {"position": [5, 4], "colour": "blue", "status": "off"},
    {"position": [5, 5], "colour": "white", "status": "off"},
    {"position": [5, 6], "colour": "white", "status": "off"},
    {"position": [5, 7], "colour": "blue", "status": "off"},
    {"position": [5, 8], "colour": "blue", "status": "off"},
    {"position": [5, 9], "colour": "blue", "status": "off"},
    {"position": [5, 10], "colour": "blue", "status": "off"},
    {"position": [5, 11], "colour": "blue", "status": "off"},
    // row 7
    {"position": [6, 0], "colour": "blue", "status": "off"},
    {"position": [6, 1], "colour": "blue", "status": "off"},
    {"position": [6, 2], "colour": "blue", "status": "off"},
    {"position": [6, 3], "colour": "blue", "status": "off"},
    {"position": [6, 4], "colour": "blue", "status": "off"},
    {"position": [6, 5], "colour": "white", "status": "off"},
    {"position": [6, 6], "colour": "white", "status": "off"},
    {"position": [6, 7], "colour": "blue", "status": "off"},
    {"position": [6, 8], "colour": "blue", "status": "off"},
    {"position": [6, 9], "colour": "blue", "status": "off"},
    {"position": [6, 10], "colour": "blue", "status": "off"},
    {"position": [6, 11], "colour": "blue", "status": "off"},
    // row 8
    {"position": [7, 0], "colour": "blue", "status": "off"},
    {"position": [7, 1], "colour": "blue", "status": "off"},
    {"position": [7, 2], "colour": "blue", "status": "off"},
    {"position": [7, 3], "colour": "blue", "status": "off"},
    {"position": [7, 4], "colour": "white", "status": "off"},
    {"position": [7, 5], "colour": "white", "status": "off"},
    {"position": [7, 6], "colour": "white", "status": "off"},
    {"position": [7, 7], "colour": "white", "status": "off"},
    {"position": [7, 8], "colour": "blue", "status": "off"},
    {"position": [7, 9], "colour": "blue", "status": "off"},
    {"position": [7, 10], "colour": "blue", "status": "off"},
    {"position": [7, 11], "colour": "blue", "status": "off"},
    // row 9
    {"position": [8, 0], "colour": "blue", "status": "off"},
    {"position": [8, 1], "colour": "blue", "status": "off"},
    {"position": [8, 2], "colour": "blue", "status": "off"},
    {"position": [8, 3], "colour": "white", "status": "off"},
    {"position": [8, 4], "colour": "white", "status": "off"},
    {"position": [8, 5], "colour": "blue", "status": "off"},
    {"position": [8, 6], "colour": "blue", "status": "off"},
    {"position": [8, 7], "colour": "white", "status": "off"},
    {"position": [8, 8], "colour": "white", "status": "off"},
    {"position": [8, 9], "colour": "blue", "status": "off"},
    {"position": [8, 10], "colour": "blue", "status": "off"},
    {"position": [8, 11], "colour": "blue", "status": "off"},
    // row 10
    {"position": [9, 0], "colour": "blue", "status": "off"},
    {"position": [9, 1], "colour": "blue", "status": "off"},
    {"position": [9, 2], "colour": "white", "status": "off"},
    {"position": [9, 3], "colour": "white", "status": "off"},
    {"position": [9, 4], "colour": "blue", "status": "off"},
    {"position": [9, 5], "colour": "blue", "status": "off"},
    {"position": [9, 6], "colour": "blue", "status": "off"},
    {"position": [9, 7], "colour": "blue", "status": "off"},
    {"position": [9, 8], "colour": "white", "status": "off"},
    {"position": [9, 9], "colour": "white", "status": "off"},
    {"position": [9, 10], "colour": "blue", "status": "off"},
    {"position": [9, 11], "colour": "blue", "status": "off"},
    // row 11
    {"position": [10, 0], "colour": "blue", "status": "off"},
    {"position": [10, 1], "colour": "white", "status": "off"},
    {"position": [10, 2], "colour": "white", "status": "off"},
    {"position": [10, 3], "colour": "blue", "status": "off"},
    {"position": [10, 4], "colour": "blue", "status": "off"},
    {"position": [10, 5], "colour": "blue", "status": "off"},
    {"position": [10, 6], "colour": "blue", "status": "off"},
    {"position": [10, 7], "colour": "blue", "status": "off"},
    {"position": [10, 8], "colour": "blue", "status": "off"},
    {"position": [10, 9], "colour": "white", "status": "off"},
    {"position": [10, 10], "colour": "white", "status": "off"},
    {"position": [10, 11], "colour": "blue", "status": "off"},
    // row 12
    {"position": [11, 0], "colour": "white", "status": "off"},
    {"position": [11, 1], "colour": "white", "status": "off"},
    {"position": [11, 2], "colour": "blue", "status": "off"},
    {"position": [11, 3], "colour": "blue", "status": "off"},
    {"position": [11, 4], "colour": "blue", "status": "off"},
    {"position": [11, 5], "colour": "blue", "status": "off"},
    {"position": [11, 6], "colour": "blue", "status": "off"},
    {"position": [11, 7], "colour": "blue", "status": "off"},
    {"position": [11, 8], "colour": "blue", "status": "off"},
    {"position": [11, 9], "colour": "blue", "status": "off"},
    {"position": [11, 10], "colour": "white", "status": "off"},
    {"position": [11, 11], "colour": "white", "status": "off"},
  ]
},
{
  "id": 2,
  "name": "Italy",
  "flagLEDs":[
    {"position": [0, 1], "colour": "red", "status": "off"},
    {"position": [0, 2], "colour": "red", "status": "off"}
  ]
}

]
)
